# Generated by Django 3.0.4 on 2020-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_p', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_p',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product_p',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product_p',
            name='price',
        ),
        migrations.AddField(
            model_name='product_p',
            name='category_toner',
            field=models.CharField(default='-', max_length=64, verbose_name='토너종류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='입고수량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='name_printer',
            field=models.CharField(default='', max_length=64, verbose_name='사용프린터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='name_toner',
            field=models.CharField(default='', max_length=64, verbose_name='토너명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='out_description',
            field=models.CharField(default='', max_length=64, verbose_name='출고내역'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='out_stock',
            field=models.IntegerField(default=0, verbose_name='출고수량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='pre_stock',
            field=models.IntegerField(default=0, verbose_name='전월재고'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_p',
            name='remark',
            field=models.CharField(default='', max_length=64, verbose_name='비고'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_p',
            name='stock',
            field=models.IntegerField(verbose_name='현재재고'),
        ),
    ]
