# Generated by Django 3.0.4 on 2020-03-09 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_p', '0002_auto_20200308_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_p',
            old_name='register_date',
            new_name='register_date_start',
        ),
        migrations.AddField(
            model_name='product_p',
            name='register_date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
