# Generated by Django 3.0.4 on 2020-03-13 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_printer', models.CharField(max_length=64, verbose_name='사용프린터')),
                ('color_printer', models.CharField(max_length=64, verbose_name='프린터색상')),
                ('name_toner', models.CharField(max_length=64, verbose_name='토너명')),
                ('color_toner', models.CharField(max_length=64, verbose_name='토너색상')),
                ('category_toner', models.CharField(max_length=64, verbose_name='토너종류')),
                ('stock', models.IntegerField(verbose_name='현재재고')),
                ('register_date', models.DateField()),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'product_p',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=128),
        ),
    ]
