# Generated by Django 3.0.4 on 2020-03-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200313_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=64, verbose_name='사용프린터')),
                ('color_product', models.CharField(max_length=64, verbose_name='프린터색상')),
                ('stock', models.IntegerField(verbose_name='현재재고')),
                ('register_date', models.DateField()),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'product',
            },
        ),
    ]
