# Generated by Django 3.0.4 on 2020-03-21 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='etc',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='비고'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='입고량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='out_stock',
            field=models.IntegerField(default=0, verbose_name='출고량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pre_stock',
            field=models.IntegerField(default=0, verbose_name='전월재고'),
            preserve_default=False,
        ),
    ]
