# Generated by Django 3.0.4 on 2020-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200321_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pre_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='month_in',
            field=models.IntegerField(default=0, verbose_name='해당월입고량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='month_out',
            field=models.IntegerField(default=0, verbose_name='해당월출고량'),
            preserve_default=False,
        ),
    ]
