# Generated by Django 3.0.4 on 2020-03-08 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_n', '0001_initial'),
        ('product_p', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_p', models.IntegerField(verbose_name='수량')),
                ('quantity_n', models.IntegerField(verbose_name='수량')),
                ('register_date', models.DateField()),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='등록날짜')),
                ('product_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_n.Product_n', verbose_name='상품')),
                ('product_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_p.Product_p', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'order',
            },
        ),
    ]
