# Generated by Django 3.0.4 on 2020-03-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=64, verbose_name='사용프린터')),
                ('color_product', models.CharField(max_length=64, verbose_name='프린터색상')),
                ('in_stock', models.IntegerField(verbose_name='입고량')),
                ('out_stock', models.IntegerField(verbose_name='출고량')),
                ('month_in', models.IntegerField(verbose_name='해당월입고량')),
                ('month_out', models.IntegerField(verbose_name='해당월출고량')),
                ('stock', models.IntegerField(verbose_name='현재재고')),
                ('description', models.TextField(verbose_name='내용')),
                ('etc', models.TextField(verbose_name='비고')),
                ('register_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'product',
            },
        ),
    ]
